// src/config/sliders.js
export const sliderConfigs = [
  {
    propKey: "x",
    isGlobal: true,
    min: -48,
    max: 48,
    defaultValue: 0,
    leftIconId: "gb-look_left",
    rightIconId: "gb-look_left",
    leftClasses: "custom left_btn oppositeX smaller_icon",
    rightClasses: "custom smaller_icon",
  },
  {
    propKey: "y",
    isGlobal: true,
    min: -60,
    max: 60,
    defaultValue: 0,
    leftIconId: "gb-look_up",
    rightIconId: "gb-look_up",
    leftClasses: "custom left_btn smaller_icon",
    rightClasses: "custom smaller_icon oppositeY",
  },
  {
    propKey: "topH",
    isGlobal: false,
    min: 0,
    max: 50,
    defaultValue: 0,
    leftIconId: "gb-base_emo",
    rightIconId: "gb-top_lid",
    leftClasses: "custom left_btn normal_icon oppositeY",
    rightClasses: "custom normal_icon oppositeY",
  },
  {
    propKey: "botH",
    isGlobal: false,
    min: 0,
    max: 50,
    defaultValue: 0,
    leftIconId: "gb-base_emo",
    rightIconId: "gb-bottom_lid",
    leftClasses: "custom left_btn normal_icon oppositeY",
    rightClasses: "custom normal_icon oppositeY",
  },
  {
    propKey: "tilt",
    isGlobal: false,
    min: -60,
    max: 60,
    defaultValue: 0,
    leftIconId: "gb-sad",
    rightIconId: "gb-angry",
    leftClasses: "custom left_btn normal_icon",
    rightClasses: "custom normal_icon",
  },
  {
    propKey: "eR",
    isGlobal: false,
    min: 0,
    max: 50,
    defaultValue: 45,
    leftIconId: "gb-eye_small",
    rightIconId: "gb-eye_large",
    leftClasses: "custom left_btn normal_icon",
    rightClasses: "custom normal_icon",
  },
  {
    propKey: "pR",
    isGlobal: false,
    min: 0,
    max: 52,
    defaultValue: 30,
    leftIconId: "gb-pupil_small",
    rightIconId: "gb-base_emo",
    leftClasses: "custom left_btn normal_icon",
    rightClasses: "custom normal_icon",
  },
];